apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openreview

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - ingress.yaml

images:
  - name: openreview
    newName: swr.eu-de.otc.t-systems.com/stackmon/openreview
    newTag: sha-235368c

labels:
  - pairs:
      app.kubernetes.io/instance: preprod
      app.kubernetes.io/managed-by: argocd
      environment: preprod
