apiVersion: v1
kind: Secret
metadata:
  name: metrics-processor-oidc
  labels:
    app.kubernetes.io/name: metrics-processor
    app.kubernetes.io/component: convertor-reporter
type: Opaque
stringData:
  service-account.json: "<path:secret/data/stackmon/metrics-processor?field=zitadel-profile>"
