apiVersion: v1
kind: Service
metadata:
  name: openreview
  labels:
    app.kubernetes.io/name: openreview
spec:
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: openreview
